
# Note: add --enable--config in the `~/.config/Code/User/settings.json`'s' `clangd.arguments`, for example:
#{
#  "clangd.arguments": [..., "--enable-config"]
#}
CompileFlags:
  Add: [-Wall, -Wextra, -Wshadow, -Wnon-virtual-dtor, -Wold-style-cast, -Wcast-align, -Woverloaded-virtual, -Wpedantic, -Wconversion, -Wsign-conversion, -Wnull-dereference, -Wdouble-promotion, -Wformat=2]
Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add: [performance*, modernize*, readability*, bugprone*, clang-analyzer*, cppcoreguidelines*, google*, hicpp*, misc*]
    Remove:
      - cppcoreguidelines-avoid-magic-numbers
      - cppcoreguidelines-init-variables
      - cppcoreguidelines-non-private-member-variables-in-classes
      - misc-non-private-member-variables-in-classes
      - readability-convert-member-functions-to-static
      - readability-identifier-length
      - readability-magic-numbers
      - readability-redundant-access-specifiers
Hover:
  ShowAKA: Yes
InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
